### ISSUE TITLE
Exception occurred while initializing handler of thing  HANDLER_INITIALIZING_ERROR

### ISSUE THREAD

**Issue by jorampic** [cedricboon/openhab2-addons#20]
## Expected Behavior
Version 2.4.0 no problem (only no vmb1ts)
with version 2.5.1, some connections do not work

## Current Behavior
![image](https://user-images.githubusercontent.com/15743943/73609922-95638f00-45d2-11ea-9bb7-66ef54c7399d.png)

## Possible Solution

use old version 2.4.0
## Steps to Reproduce (for Bugs)

Log : 

```
2020-02-02 14:40:26.500 [me.event.InboxRemovedEvent] - Discovery Result with UID 'velbus:vmbdmi:ae2fda98:65' has been removed.

2020-02-02 14:40:26.500 [hingStatusInfoChangedEvent] - 'velbus:vmbdmi:ae2fda98:65' changed from UNINITIALIZED to INITIALIZING

2020-02-02 14:40:26.505 [hingStatusInfoChangedEvent] - 'velbus:vmbdmi:ae2fda98:65' changed from INITIALIZING to OFFLINE (BRIDGE_OFFLINE)

==> /var/log/openhab2/openhab.log <==

2020-02-02 14:40:26.506 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.initialize()' on 'org.openhab.binding.velbus.internal.handler.VelbusDimmerHandler@4408eae1': null

java.lang.NullPointerException: null

	at org.openhab.binding.velbus.internal.handler.VelbusThingHandler.initializeChannelStates(VelbusThingHandler.java:153) ~[?:?]

	at org.openhab.binding.velbus.internal.handler.VelbusThingHandler.initialize(VelbusThingHandler.java:70) ~[?:?]

	at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source) ~[?:?]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]

	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]

	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

==> /var/log/openhab2/events.log <==

2020-02-02 14:40:26.506 [me.event.ThingUpdatedEvent] - Thing 'velbus:vmbdmi:ae2fda98:65' has been updated.

==> /var/log/openhab2/openhab.log <==

2020-02-02 14:40:26.508 [ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred while initializing handler of thing 'velbus:vmbdmi:ae2fda98:65': null

java.lang.NullPointerException: null

	at org.openhab.binding.velbus.internal.handler.VelbusThingHandler.initializeChannelStates(VelbusThingHandler.java:153) ~[?:?]

	at org.openhab.binding.velbus.internal.handler.VelbusThingHandler.initialize(VelbusThingHandler.java:70) ~[?:?]

	at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source) ~[?:?]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]

	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]

	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

==> /var/log/openhab2/events.log <==

2020-02-02 14:40:26.508 [hingStatusInfoChangedEvent] - 'velbus:vmbdmi:ae2fda98:65' changed from OFFLINE (BRIDGE_OFFLINE) to UNINITIALIZED (HANDLER_INITIALIZING_ERROR)
```

## Your Environment

* Version used: openHAB 2.5.0

**Comment by cedricboon** [comment]
Hi, did you try to delete the "Things" and re-discover them?

**Comment by jorampic** [comment]
i used a new install of openhab still the same problem : 
![image](https://user-images.githubusercontent.com/15743943/74610915-b6120580-50f7-11ea-97a8-4f656d60057e.png)

**Comment by MDAR** [comment]
Hi

Just to be clear.

Is this a fresh installation of openHAB2 on a new machine, or a reinstall ?


Can you check in Karaf that there is only 1 version of the binding loaded, even if you only have 1 JAR file.

Then restart the Velbus binding

**Comment by jorampic** [comment]
new install and i used a different gateway to velbus ( velserv ) error still exists

**Comment by jorampic** [comment]
update to Version 
278 │ Active  │  80 │ 2.5.4.202003281629      │ openHAB Add-ons :: Bundles :: Velbus Binding

no more problem
